# Generated by Django 4.2.9 on 2026-02-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certification_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='Direct', max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
