# Generated by Django 4.2.9 on 2026-02-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
