# Generated by Django 4.2.9 on 2026-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_achievement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordering index (lower numbers show first)'),
        ),
    ]
