# Generated by Django 4.2.9 on 2026-05-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
