# Generated by Django 4.2.9 on 2026-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order', '-date']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', '-year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordering index (lower numbers show first)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordering index (lower numbers show first)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordering index (lower numbers show first)'),
        ),
    ]
