# Generated by Django 4.2.9 on 2026-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='satisfaction_rate',
            field=models.CharField(default='100%', max_length=50),
        ),
    ]
