# Generated by Django 4.2.9 on 2026-05-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_satisfaction_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('first_visited', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
