# Generated by Django 5.0 on 2026-05-19
import uuid
from django.db import migrations
from django.db.models import Min, Max, Count

def backfill_unique_visitors(apps, schema_editor):
    SiteVisit = apps.get_model('core', 'SiteVisit')
    UniqueVisitor = apps.get_model('core', 'UniqueVisitor')

    # Get all SiteVisits where device_id is NULL or empty
    untracked_visits = SiteVisit.objects.filter(device_id__isnull=True)
    if not untracked_visits.exists():
        return

    # Find unique user agents to group historical visits by device
    user_agents = untracked_visits.values_list('user_agent', flat=True).distinct()

    for ua in user_agents:
        ua_value = ua if ua else "Unknown User Agent"

        # Generate a stable, deterministic UUID based on the user agent string
        stable_device_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, ua_value))

        # Query all visits for this user agent
        ua_visits = untracked_visits.filter(user_agent=ua)
        
        # Aggregate dates and count
        stats = ua_visits.aggregate(
            first_visit=Min('timestamp'),
            last_visit=Max('timestamp'),
            total_count=Count('id')
        )

        first_visited = stats['first_visit']
        last_visited = stats['last_visit']
        visit_count = stats['total_count']

        # Update all these visits to have our new stable_device_id
        ua_visits.update(device_id=stable_device_id)

        # Create or update UniqueVisitor
        visitor, created = UniqueVisitor.objects.get_or_create(
            device_id=stable_device_id,
            defaults={
                'visit_count': visit_count
            }
        )
        
        # Use database-level .update() to set timestamps and bypass Django's auto_now / auto_now_add restrictions
        if created:
            UniqueVisitor.objects.filter(pk=visitor.pk).update(
                first_visited=first_visited,
                last_visited=last_visited
            )
        else:
            new_first = min(first_visited, visitor.first_visited) if first_visited else visitor.first_visited
            new_last = max(last_visited, visitor.last_visited) if last_visited else visitor.last_visited
            UniqueVisitor.objects.filter(pk=visitor.pk).update(
                first_visited=new_first,
                last_visited=new_last,
                visit_count=visitor.visit_count + visit_count
            )

def reverse_backfill(apps, schema_editor):
    # Leaving device_ids in SiteVisit on rollback is safe, no destructive actions needed.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_uniquevisitor_sitevisit_device_id'),
    ]

    operations = [
        migrations.RunPython(backfill_unique_visitors, reverse_code=reverse_backfill),
    ]
