# Generated by Django 4.2.9 on 2026-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_resume_resumedownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Suresh_Polai_Resume', help_text='This will be the download filename', max_length=200),
        ),
    ]
